# Generated by Django 5.2.10 on 2026-01-14 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('service', 'SERVICE'), ('division', 'DIVISION'), ('labo_pedagogique', 'LABO_PEDAGOGIQUE'), ('labo_recherche', 'LABO_RECHERCHE'), ('atelier', 'ATELIER')], default='service', max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('actif', 'ACTIF'), ('non_actif', 'NON_ACTIF')], default='actif', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_services', to='Service.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('employe', 'EMPLOYE'), ('chef', 'CHEF')], default='employe', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('actif', 'ACTIF'), ('non_actif', 'NON_ACTIF')], default='actif', max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
